"""
audit_database.py — Audits and repairs the textbook_questions table for:
1. Mojibake (Encoding issues)
2. Formatting artifacts (weird bullets, excessive spacing)
3. Structural issues (empty stems, duplicate entries)
4. LaTeX inconsistencies
"""

import os
import re
import json
from dotenv import load_dotenv
from supabase import create_client

load_dotenv()

SUPABASE_URL = "https://bodwvpqtfhqmpzialpig.supabase.co"
SUPABASE_KEY = os.environ.get("SUPABASE_SERVICE_KEY", "")
supabase = create_client(SUPABASE_URL, SUPABASE_KEY)

def repair_mojibake(s):
    if not s: return s
    try:
        if "â" in s:
            return s.encode('cp1252').decode('utf-8')
    except:
        pass
    # Manual fallback for common ones if re-encode fails
    replacements = {"â€“": "–", "â€™": "’", "â€œ": "“", "â€": "”", "â€¦": "…"}
    for old, new in replacements.items():
        s = s.replace(old, new)
    return s

def clean_formatting(s):
    if not s: return s
    
    # 0. Strip leading question numbers (e.g., "18. As a result" -> "As a result")
    # Matches a number at the start followed by dot and optional space
    s = re.sub(r'^\d+\.\s*', '', s)

    # 1. Standardize bullets
    s = re.sub(r'([■●•·])(?!\s)', r'\1 ', s)
    
    # 2. Fix spacing
    s = re.sub(r'[ \t]{3,}', ' ', s)

    # 3. Fix double-backslash escaped dollar signs (often generated by VLMs)
    # Conversion: $\\$R$ -> $\$R$
    s = s.replace(r'$\\$', r'$ \$') # Adding a small space or just fix the escape
    # Better: just fix the escape
    s = s.replace(r'\\$', r'\$')
    
    # 4. Trim lines
    s = "\n".join(line.strip() for line in s.splitlines())
    
    return s.strip()

def repair_node(node):
    if not isinstance(node, dict): return node
    if "text" in node: node["text"] = clean_formatting(repair_mojibake(node["text"]))
    if "answer" in node: node["answer"] = clean_formatting(repair_mojibake(node["answer"]))
    if "subparts" in node:
        for k, v in node["subparts"].items():
            node["subparts"][k] = repair_node(v)
    return node

def main():
    print("Fetching all questions for comprehensive audit...")
    result = supabase.table("textbook_questions").select("*").execute()
    rows = result.data
    print(f"Auditing {len(rows)} rows...\n")

    stats = {
        "mojibake_fixed": 0,
        "formatting_cleaned": 0,
        "empty_stems": [],
        "duplicate_check": {},
        "latex_warnings": []
    }

    for row in rows:
        rid = row["id"]
        ex = row["exercise"]
        num = row["question_number"]
        stem = row["question_text"]
        parts = row["parts"]
        ans = row["answer_text"]

        # 1. Audit Stem
        new_stem = clean_formatting(repair_mojibake(stem))
        
        # 2. Audit Parts
        new_parts = {}
        if parts:
            for label, node in parts.items():
                new_parts[label] = repair_node(dict(node))
        
        # 3. Audit Answer
        new_ans = clean_formatting(repair_mojibake(ans))

        # Check for changes
        changed = False
        if new_stem != stem:
            if "â" in stem: stats["mojibake_fixed"] += 1
            else: stats["formatting_cleaned"] += 1
            changed = True
        
        if json.dumps(new_parts) != json.dumps(parts):
            changed = True
        
        if new_ans != ans:
            changed = True

        if changed:
            print(f"Updating Ex {ex} Q{num}...")
            supabase.table("textbook_questions").update({
                "question_text": new_stem,
                "parts": new_parts,
                "answer_text": new_ans
            }).eq("id", rid).execute()

        # 4. Collection Invariants/Warnings
        if not new_stem and not new_parts:
            stats["empty_stems"].append(f"Ex {ex} Q{num}")
        
        key = (ex, num)
        if key in stats["duplicate_check"]:
            stats["duplicate_check"][key].append(rid)
        else:
            stats["duplicate_check"][key] = [rid]

        # LaTeX check (mismatched $ - ignore escaped \$)
        if new_stem:
            # Strip escaped \$ first
            unescaped = new_stem.replace(r'\$', '')
            if unescaped.count('$') % 2 != 0:
                stats["latex_warnings"].append(f"Ex {ex} Q{num} (Stem)")

    print("\n" + "="*40)
    print("AUDIT & REPAIR SUMMARY")
    print("="*40)
    print(f"Mojibake issues resolved   : {stats['mojibake_fixed']}")
    print(f"Formatting tweaks applied  : {stats['formatting_cleaned']}")
    
    dupes = [f"{k[0]} Q{k[1]}" for k, v in stats["duplicate_check"].items() if len(v) > 1]
    print(f"Duplicate questions found  : {len(dupes)} ({', '.join(dupes) if dupes else 'None'})")
    
    print(f"Empty questions (no text)  : {len(stats['empty_stems'])}")
    if stats['empty_stems']:
        print(f"  - {', '.join(stats['empty_stems'][:10])}...")

    print(f"LaTeX Mismatches ($ count) : {len(stats['latex_warnings'])}")
    if stats['latex_warnings']:
        print(f"  - {', '.join(stats['latex_warnings'][:10])}...")
    print("="*40)

if __name__ == "__main__":
    main()
